name: 阿里云盘
on:
  workflow_dispatch:
  schedule:
    - cron: '15 10 31 1,3,5,7,8,10,12 *'
    - cron: '15 10 28,29 2 *'
    - cron: '15 10 30 4,6,9,11 *'
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          status=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Whiskium/SurveyCorps/actions/workflows/alipan.yml/runs | jq -r ".workflow_runs[0].conclusion")
          echo $status
          if [ $status -eq 'failure' ]; then
            exit 1
          fi