name: 云闪付
on:
  workflow_dispatch:
  schedule:
    - cron: '15 23 * * *'
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          status=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Whiskium/SurveyCorps/actions/workflows/UnionPay.yml/runs | jq -r ".workflow_runs[0].conclusion")
          echo $status
          if [ $status == 'failure' ]; then
            exit 1
          fi